version: 2
jobs:
  build:
    working_directory: ~/flowspace-bakery
    docker:
      - image: ruby:2.6.2
        environment:
          DATABASE_URL: postgresql://ubuntu@localhost/flowspace-bakery_test?sslmode=disable
          RAILS_ENV: test
          RACK_ENV: test
      - image: postgres:9.6.2
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: flowspace-bakery_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - restore_cache:
          keys:
          - flowspace-bakery-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          - flowspace-bakery-master-{{ checksum "Gemfile.lock" }}
      - run:
          name: install nodejs and npm
          command: |
            curl -sSL "https://nodejs.org/dist/v12.18.4/node-v12.18.4-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v11.10.0-linux-x64/bin/node
            curl https://www.npmjs.com/install.sh | sudo bash
      - run:
          name: bundle install
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - save_cache:
          key: flowspace-bakery-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - "~/flowspace-bakery/vendor/bundle"
      - run:
          name: set up database
          command: bundle exec rake db:create db:schema:load --trace
      - run:
          name: results folder
          command: mkdir /tmp/test-reports
      - run:
          name: rspec
          command: bundle exec rspec --color --require rails_helper --format RspecJunitFormatter --out /tmp/test-reports/rspec.xml spec --format progress
      - store_artifacts:
          path: /tmp/artifacts
          destination: build
      - store_test_results:
          path: /tmp/test-reports
